version: "3"
services:

   gohttpserver:
     image: codeskyblue/gohttpserver
     container_name: gohttpserver
     restart: always
     privileged: true
     ports:
      - "8095:8000"
     volumes:
      - ./share:/app/public
